export { default as border } from "./img/Border.png";
export { default as book } from "./img/book.png";
export { default as line } from "./img/Line.png";
export { default as BookIcon } from "./svg/bookIcon.svg?react";
export { default as HomeIcon } from "./svg/Home.svg?react";
export { default as ChatIcon } from "./svg/Chat Bubble.svg?react";
export { default as SearchIcon } from "./svg/fe_search.svg?react";
export { default as ProfileIcon } from "./svg/profile.svg?react";
export { default as ProfileImage } from "./img/profile.png";
export { default as PlusBtn } from "./svg/plusBtn.svg?react";
export { default as CloseBtn } from "./svg/closeBtn.svg?react";
